spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 348164436585-css8fvtrharhbof4t6b72h5fahtt2tvp.apps.googleusercontent.com
            client-secret: QNCJ3XkB8yjixMTSAR1yVyU3
            scope:
            - email
            - profile